[package]
name = "slack-emoji-exporter"
version = "0.1.0"
authors = ["Steve Franchak <stevefranchak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3.0"
clap = "3.0.0-beta.2"
futures = "0.3.8"
reqwest = { version = "0.10.8", features = ["json"] }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
# Need to use an older version of tokio because of reqwest
tokio = { version = "0.2.22", features = ["macros"] }
