name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
      - uses: actions/setup-python@v2
      - name: Double-check nothing got through pre-commit
        uses: pre-commit/action@v2.0.0
      - name: Try release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Run tests
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
