name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
      - name: Try release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
